version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    working_dir: /application
    volumes:
      - ${ROOT_PATH}:/application
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: mariadb:10.3.3
    container_name: ${APP_NAME}-db
    working_dir: /application
    env_file:
      - ./docker-database.env
    ports:
      - "3306:3306"

  api:
    build: ./api
    container_name: ${APP_NAME}-api
    working_dir: /application
    volumes:
      - ${ROOT_PATH}:/application
      - ./api/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    ports:
      - "9000:9000"

  web:
    build:
      context: ${ROOT_PATH}
      dockerfile: ./docker/dev/web/Dockerfile
    container_name: ${APP_NAME}-web
    working_dir: /application
    ports:
      - "3000:3000"
    volumes:
      - ${ROOT_PATH}/web:/application
    environment:
      - CHOKIDAR_USEPOLLING=true
