// Boards
export const LOAD_BOARDS_SUCCESS = "LOAD_BOARDS_SUCCESS";
export const LOAD_BOARD_SUCCESS = "LOAD_BOARD_SUCCESS";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";

// Sections
export const LOAD_SECTIONS_SUCCESS = "LOAD_SEACTIONS_SUCCESS";
export const CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";
export const REORDER_SECTION_SUCCESS = "REORDER_SECTION_SUCCESS";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const INVALIDATE_SECTIONS_STATE = "INVALIDATE_SECTIONS_STATE";

// TASKS
export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const REORDER_TASK_SUCCESS = "REORDER_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const INVALIDATE_TASKS_STATE = "INVALIDATE_TASKS_STATE";
