-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 18:58:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce_template_local
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
                                      `id` INT NOT NULL AUTO_INCREMENT,
                                      `email` VARCHAR(255) NOT NULL,
    `username` VARCHAR(45) NOT NULL,
    `password_hash` VARCHAR(255) NULL,
    `password_reset_token` VARCHAR(255) NULL,
    `verification_token` VARCHAR(255) NULL,
    `auth_key` VARCHAR(255) NULL,
    `status` INT NOT NULL DEFAULT 9,
    `first_name` VARCHAR(45) NULL,
    `last_name` VARCHAR(45) NULL,
    `address` VARCHAR(255) NULL,
    `city` VARCHAR(45) NULL,
    `country` VARCHAR(45) NULL,
    `zip` INT NULL,
    `created_at` INT NULL,
    `created_by` INT NULL,
    `updated_at` INT NULL,
    `updated_by` INT NULL,
    `is_deleted` TINYINT NULL DEFAULT 0,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `file` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `image_id` INT(11) NULL DEFAULT NULL,
    `original_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
    `mime_type` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
    `storage_type` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
    `storage_key` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
    `size` INT(11) NULL DEFAULT NULL,
    `created_at` INT(11) NULL DEFAULT NULL,
    `created_by` INT(11) NULL DEFAULT NULL,
    `updated_at` INT(11) NULL DEFAULT NULL,
    `updated_by` INT(11) NULL DEFAULT NULL,
    `is_deleted` INT(11) NULL DEFAULT 0,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `image` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `original_name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
    `mime_type` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
    `size` INT(11) NOT NULL,
    `storage_type` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
    `storage_key` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
    `height` INT(11) NULL DEFAULT NULL,
    `width` INT(11) NULL DEFAULT NULL,
    `created_at` INT(11) NULL DEFAULT NULL,
    `created_by` INT(11) NULL DEFAULT NULL,
    `updated_at` INT(11) NULL DEFAULT NULL,
    `updated_by` INT(11) NULL DEFAULT NULL,
    `is_deleted` INT(11) NULL DEFAULT 0,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `image_thumb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `image_thumb` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `image_id` INT(11) NOT NULL,
    `spec_key` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
    `storage_type` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
    `storage_key` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
    `created_at` INT(11) NULL DEFAULT NULL,
    `created_by` INT(11) NULL DEFAULT NULL,
    `updated_at` INT(11) NULL DEFAULT NULL,
    `updated_by` INT(11) NULL DEFAULT NULL,
    `is_deleted` INT(11) NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `fk_image_thumb_image_idx` (`image_id` ASC),
    CONSTRAINT `fk_image_thumb_image`
    FOREIGN KEY (`image_id`)
    REFERENCES `image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
